//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Dictionary", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/About.
        /// </summary>
        internal static string lnkAbout {
            get {
                return ResourceManager.GetString("lnkAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Blog.
        /// </summary>
        internal static string lnkBlog {
            get {
                return ResourceManager.GetString("lnkBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/BlogDetail.
        /// </summary>
        internal static string lnkBlogDetail {
            get {
                return ResourceManager.GetString("lnkBlogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Contact.
        /// </summary>
        internal static string lnkContact {
            get {
                return ResourceManager.GetString("lnkContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Index.
        /// </summary>
        internal static string lnkIndex {
            get {
                return ResourceManager.GetString("lnkIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Project.
        /// </summary>
        internal static string lnkProject {
            get {
                return ResourceManager.GetString("lnkProject", resourceCulture);
            }
        }
    }
}
